### ISSUE TITLE
XML errors when upgrading to Magento 2.2.4

### ISSUE THREAD

**Issue by nopenopenope** [magefan/module-blog#159]
Hi,

after upgrading to Magento2.2.4 and updating your extension, I get this in frontend:
```

1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'argument': This element is not expected. Expected is one of ( action, arguments, block, container, referenceBlock, uiComponent ).
Line: 774

Element 'referenceContainer', attribute 'after': The attribute 'after' is not allowed.
Line: 890

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magefan\Blog\Block\Index' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 891

Element 'block', attribute 'class': '\Magefan\Blog\Block\Index' is not a valid value of the atomic type 'blockClassType'.
Line: 891

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magefan\Blog\Block\Post\PostList\Item' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 894

Element 'block', attribute 'class': '\Magefan\Blog\Block\Post\PostList\Item' is not a valid value of the atomic type 'blockClassType'.
Line: 894

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magefan\Blog\Block\Post\Info' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 895

Element 'block', attribute 'class': '\Magefan\Blog\Block\Post\Info' is not a valid value of the atomic type 'blockClassType'.
Line: 895

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magefan\Blog\Block\Post\PostList\Toolbar' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 900

Element 'block', attribute 'class': '\Magefan\Blog\Block\Post\PostList\Toolbar' is not a valid value of the atomic type 'blockClassType'.
Line: 900

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magefan\Blog\Block\Post\PostList\Toolbar\Pager' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 901

Element 'block', attribute 'class': '\Magefan\Blog\Block\Post\PostList\Toolbar\Pager' is not a valid value of the atomic type 'blockClassType'.
Line: 901

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magefan\Blog\Block\Post\View' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 911

Element 'block', attribute 'class': '\Magefan\Blog\Block\Post\View' is not a valid value of the atomic type 'blockClassType'.
Line: 911

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magefan\Blog\Block\Post\Info' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 912

Element 'block', attribute 'class': '\Magefan\Blog\Block\Post\Info' is not a valid value of the atomic type 'blockClassType'.
Line: 912

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magento\Framework\View\Element\Text\ListText' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 916

Element 'block', attribute 'class': '\Magento\Framework\View\Element\Text\ListText' is not a valid value of the atomic type 'blockClassType'.
Line: 916

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magefan\Blog\Block\Post\View\RelatedPosts' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 917

Element 'block', attribute 'class': '\Magefan\Blog\Block\Post\View\RelatedPosts' is not a valid value of the atomic type 'blockClassType'.
Line: 917

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magefan\Blog\Block\Post\View\RelatedProducts' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 918

Element 'block', attribute 'class': '\Magefan\Blog\Block\Post\View\RelatedProducts' is not a valid value of the atomic type 'blockClassType'.
Line: 918

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magefan\Blog\Block\Post\View\Comments' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 919

Element 'block', attribute 'class': '\Magefan\Blog\Block\Post\View\Comments' is not a valid value of the atomic type 'blockClassType'.
Line: 919


Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'argument': This element is not expected. Expected is one of ( action, arguments, block, container, referenceBlock, uiComponent ).
Line: 774

Element 'referenceContainer', attribute 'after': The attribute 'after' is not allowed.
Line: 890

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magefan\Blog\Block\Index' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 891

Element 'block', attribute 'class': '\Magefan\Blog\Block\Index' is not a valid value of the atomic type 'blockClassType'.
Line: 891

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magefan\Blog\Block\Post\PostList\Item' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 894

Element 'block', attribute 'class': '\Magefan\Blog\Block\Post\PostList\Item' is not a valid value of the atomic type 'blockClassType'.
Line: 894

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magefan\Blog\Block\Post\Info' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 895

Element 'block', attribute 'class': '\Magefan\Blog\Block\Post\Info' is not a valid value of the atomic type 'blockClassType'.
Line: 895

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magefan\Blog\Block\Post\PostList\Toolbar' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 900

Element 'block', attribute 'class': '\Magefan\Blog\Block\Post\PostList\Toolbar' is not a valid value of the atomic type 'blockClassType'.
Line: 900

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magefan\Blog\Block\Post\PostList\Toolbar\Pager' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 901

Element 'block', attribute 'class': '\Magefan\Blog\Block\Post\PostList\Toolbar\Pager' is not a valid value of the atomic type 'blockClassType'.
Line: 901

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magefan\Blog\Block\Post\View' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 911

Element 'block', attribute 'class': '\Magefan\Blog\Block\Post\View' is not a valid value of the atomic type 'blockClassType'.
Line: 911

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magefan\Blog\Block\Post\Info' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 912

Element 'block', attribute 'class': '\Magefan\Blog\Block\Post\Info' is not a valid value of the atomic type 'blockClassType'.
Line: 912

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magento\Framework\View\Element\Text\ListText' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 916

Element 'block', attribute 'class': '\Magento\Framework\View\Element\Text\ListText' is not a valid value of the atomic type 'blockClassType'.
Line: 916

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magefan\Blog\Block\Post\View\RelatedPosts' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 917

Element 'block', attribute 'class': '\Magefan\Blog\Block\Post\View\RelatedPosts' is not a valid value of the atomic type 'blockClassType'.
Line: 917

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magefan\Blog\Block\Post\View\RelatedProducts' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 918

Element 'block', attribute 'class': '\Magefan\Blog\Block\Post\View\RelatedProducts' is not a valid value of the atomic type 'blockClassType'.
Line: 918

Element 'block', attribute 'class': [facet 'pattern'] The value '\Magefan\Blog\Block\Post\View\Comments' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 919

Element 'block', attribute 'class': '\Magefan\Blog\Block\Post\View\Comments' is not a valid value of the atomic type 'blockClassType'.
Line: 919

#0 /var/www/html/vendor/magento/framework/Config/Dom.php(115): Magento\Framework\Config\Dom->_initDom('<layout xmlns:x...')
#1 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\Framework\Config\Dom->__construct('<layout xmlns:x...', Object(Magento\Framework\App\Arguments\ValidationState), Array, NULL, '/var/www/html/v...', '%message%\nLine:...')
#2 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#3 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#4 /var/www/html/vendor/magento/framework/Config/DomFactory.php(42): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#5 /var/www/html/vendor/magento/framework/View/Model/Layout/Update/Validator.php(141): Magento\Framework\Config\DomFactory->createDom(Array)
#6 /var/www/html/vendor/magento/framework/View/Model/Layout/Merge.php(461): Magento\Framework\View\Model\Layout\Update\Validator->isValid('<layout xmlns:x...', 'layout_merged', false)
#7 /var/www/html/vendor/magento/framework/View/Model/Layout/Merge.php(442): Magento\Framework\View\Model\Layout\Merge->_validateMergedLayout('LAYOUT_frontend...', '<referenceConta...')
#8 /var/www/html/generated/code/Magento/Framework/View/Model/Layout/Merge/Interceptor.php(193): Magento\Framework\View\Model\Layout\Merge->load(Array)
#9 /var/www/html/vendor/magento/framework/View/Layout/Builder.php(86): Magento\Framework\View\Model\Layout\Merge\Interceptor->load()
#10 /var/www/html/vendor/magento/framework/View/Layout/Builder.php(63): Magento\Framework\View\Layout\Builder->loadLayoutUpdates()
#11 /var/www/html/vendor/magento/framework/View/Layout.php(254): Magento\Framework\View\Layout\Builder->build()
#12 /var/www/html/vendor/magento/framework/View/Layout.php(875): Magento\Framework\View\Layout->build()
#13 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('page_content_he...')
#14 /var/www/html/vendor/magento/module-cms/Helper/Page.php(171): Magento\Framework\View\Layout\Interceptor->getBlock('page_content_he...')
#15 /var/www/html/vendor/magento/module-cms/Controller/Index/Index.php(43): Magento\Cms\Helper\Page->prepareResultPage(Object(Magento\Cms\Controller\Index\Index\Interceptor), 'home')
#16 /var/www/html/generated/code/Magento/Cms/Controller/Index/Index/Interceptor.php(24): Magento\Cms\Controller\Index\Index->execute(NULL)
#17 /var/www/html/vendor/magento/framework/App/Action/Action.php(107): Magento\Cms\Controller\Index\Index\Interceptor->execute()
#18 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Cms\Controller\Index\Index\Interceptor->___callParent('dispatch', Array)
#20 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cms\Controller\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#21 /var/www/html/generated/code/Magento/Cms/Controller/Index/Index/Interceptor.php(39): Magento\Cms\Controller\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#22 /var/www/html/vendor/magento/framework/App/FrontController.php(55): Magento\Cms\Controller\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#25 /var/www/html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#26 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 /var/www/html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#30 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#31 /var/www/html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#32 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#33 /var/www/html/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#34 /var/www/html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#35 {main}


```

Magento 2.2.4
PHP 7.0.30
MariaDB 5.6

**Comment by magefan** [comment]
@nopenopenope , we have tested Magefan Blog extension v2.8.0 on Magento 2.2.4 and have not found any issues. Please try to do next:

1. Make sure that you use the latest blog version 2.8.0
2. Check the Magefan_Blog layout files in your custom theme
