### ISSUE TITLE
Not compatible with Full Page Caching

### ISSUE THREAD

**Issue by grasdaggel** [magefan/module-blog#32]
We are using Magefans Blog Module.

When we are activating the Full Page Cache, it triggers a HTTP 500 on the CMS home page, where we are using a implementation of it.

Modules Block Code that triggers the error:

```
/**
 * Get Block Identities
 * @return Array
 */
public function getIdentities()
{
    return [\Magento\Cms\Model\Page::CACHE_TAG . '_relatedproducts_'.$this->getPost()->getId()  ];
}
```
Error:

```
Fatal error: Uncaught Error: Call to a member function getId() on null in ```
/home/customer00014/public_html/206/app/code/Magefan/Blog/Block/Post/View/RelatedProducts.php:135
Stack trace: #0 /home/customer00014/public_html/206/var/generation/Magefan/Blog/Block/Post/View/RelatedProducts/Interceptor.php(63): Magefan\Blog\Block\Post\View\RelatedProducts->getIdentities() 
#1 /home/customer00014/public_html/206/vendor/magento/module-page-cache/Model/Layout/LayoutPlugin.php(71): Magefan\Blog\Block\Post\View\RelatedProducts\Interceptor->getIdentities() 
#2 /home/customer00014/public_html/206/vendor/magento/framework/Interception/Interceptor.php(150): Magento\PageCache\Model\Layout\LayoutPlugin->afterGetOutput(Object(Magento\Framework\View\Layout\Interceptor), ' <script>\n ...'') 
#3 /home/customer00014/public_html/206/var/generation/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array) #4 /home/customer00014/public_html/206/vendor/magento/framework/View/Result/Page.php(241): Mage in /home/customer00014/public_html/206/app/code/Magefan/Blog/Block/Post/View/RelatedProducts.php on line 135
```
In the specific .php-file theres a `->getPost()->getID()` call which triggers the error.

The question now is:

* why does the module calls a member function on null, and what does that mean?
* how can I fix this error? What would be the correct way to "get identitiers"?
* for what do I need Identities? Is it cache relevant?

**Comment by grasdaggel** [comment]
In our case, a solution would be to check wheter the displayed size is either the CMS home page or its a blog page and return unique identifiers. 

So far,
```
public function getIdentities()
    {	
	    $currentUrl = $this->getUrl('', ['_current' => true]);
	    $urlRewrite = $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
	    if($currentUrl == $urlRewrite):
	    	$random = rand(0,99999);
			return [\Magento\Cms\Model\Page::CACHE_TAG . '_relatedproducts_' . $this->getPost() . '' . $random  ];
		else:
			return [\Magento\Cms\Model\Page::CACHE_TAG . '_relatedproducts_' . $this->getPost()-getId()];
		endif;
    }
```

works for us for the homepage, but not the blog pages, where it throws another error:
```
Recoverable Error: Object of class Magefan\Blog\Model\Post could not be converted to string in /home/reisebil/public_html/206/app/code/Magefan/Blog/Block/Post/View/RelatedProducts.php on line 141
#0 /home/reisebil/public_html/206/app/code/Magefan/Blog/Block/Post/View/RelatedProducts.php(141): Magento\Framework\App\ErrorHandler->handler(4096, 'Object of class...', '/home/reisebil/...', 141, Array)
#1 /home/reisebil/public_html/206/var/generation/Magefan/Blog/Block/Post/View/RelatedProducts/Interceptor.php(63): Magefan\Blog\Block\Post\View\RelatedProducts->getIdentities()
#2 /home/reisebil/public_html/206/vendor/magento/module-page-cache/Model/Layout/LayoutPlugin.php(71): Magefan\Blog\Block\Post\View\RelatedProducts\Interceptor->getIdentities()
#3 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Interceptor.php(150): Magento\PageCache\Model\Layout\LayoutPlugin->afterGetOutput(Object(Magento\Framework\View\Layout\Interceptor), '    <script>\n  ...')
#4 /home/reisebil/public_html/206/var/generation/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#5 /home/reisebil/public_html/206/vendor/magento/framework/View/Result/Page.php(241): Magento\Framework\View\Layout\Interceptor->getOutput()
#6 /home/reisebil/public_html/206/vendor/magento/framework/View/Result/Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#7 [internal function]: Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#8 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#9 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#10 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#11 /home/reisebil/public_html/206/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#12 [internal function]: Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#13 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#14 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#15 /home/reisebil/public_html/206/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#16 [internal function]: Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#17 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#18 /home/reisebil/public_html/206/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#19 /home/reisebil/public_html/206/vendor/magento/framework/App/View.php(221): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#20 /home/reisebil/public_html/206/app/code/Magefan/Blog/Controller/Post/View.php(52): Magento\Framework\App\View->renderLayout()
#21 /home/reisebil/public_html/206/var/generation/Magefan/Blog/Controller/Post/View/Interceptor.php(24): Magefan\Blog\Controller\Post\View->execute()
#22 /home/reisebil/public_html/206/vendor/magento/framework/App/Action/Action.php(102): Magefan\Blog\Controller\Post\View\Interceptor->execute()
#23 [internal function]: Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#25 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(70): Magefan\Blog\Controller\Post\View\Interceptor->___callParent('dispatch', Array)
#26 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magefan\\Blog\\Co...', 'dispatch', Object(Magefan\Blog\Controller\Post\View\Interceptor), Array, 'designLoader')
#27 /home/reisebil/public_html/206/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#28 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magefan\Blog\Controller\Post\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#30 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magefan\\Blog\\Co...', 'dispatch', Object(Magefan\Blog\Controller\Post\View\Interceptor), Array, 'contextPlugin')
#31 /home/reisebil/public_html/206/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#32 [internal function]: Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magefan\Blog\Controller\Post\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#33 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#34 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magefan\\Blog\\Co...', 'dispatch', Object(Magefan\Blog\Controller\Post\View\Interceptor), Array, 'customer-app-ac...')
#35 /home/reisebil/public_html/206/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#36 [internal function]: Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magefan\Blog\Controller\Post\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#37 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#38 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magefan\\Blog\\Co...', 'dispatch', Object(Magefan\Blog\Controller\Post\View\Interceptor), Array, 'storeCheck')
#39 /home/reisebil/public_html/206/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#40 [internal function]: Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magefan\Blog\Controller\Post\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#41 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#42 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magefan\\Blog\\Co...', 'dispatch', Object(Magefan\Blog\Controller\Post\View\Interceptor), Array, 'weee-app-action...')
#43 /home/reisebil/public_html/206/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#44 [internal function]: Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magefan\Blog\Controller\Post\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#45 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#46 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magefan\\Blog\\Co...', 'dispatch', Object(Magefan\Blog\Controller\Post\View\Interceptor), Array, 'tax-app-action-...')
#47 /home/reisebil/public_html/206/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magefan\Blog\Controller\Post\View\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#48 [internal function]: Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magefan\Blog\Controller\Post\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#49 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#50 /home/reisebil/public_html/206/var/generation/Magefan/Blog/Controller/Post/View/Interceptor.php(39): Magefan\Blog\Controller\Post\View\Interceptor->___callPlugins('dispatch', Array, Array)
#51 /home/reisebil/public_html/206/vendor/magento/framework/App/FrontController.php(55): Magefan\Blog\Controller\Post\View\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#52 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#53 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#54 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#55 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#56 /home/reisebil/public_html/206/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(89): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#57 [internal function]: Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#58 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#59 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#60 /home/reisebil/public_html/206/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#61 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#62 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#63 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'searchautocompl...')
#64 /home/reisebil/public_html/206/vendor/mirasvit/module-search-autocomplete/src/SearchAutocomplete/Model/App/FrontController/Plugin.php(129): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#65 [internal function]: Mirasvit\SearchAutocomplete\Model\App\FrontController\Plugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#66 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#67 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#68 /home/reisebil/public_html/206/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#69 [internal function]: Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#70 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#71 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#72 /home/reisebil/public_html/206/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#73 [internal function]: Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#74 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#75 /home/reisebil/public_html/206/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#76 /home/reisebil/public_html/206/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#77 [internal function]: Magento\Framework\App\Http->launch()
#78 /home/reisebil/public_html/206/vendor/magento/framework/Interception/Interceptor.php(144): call_user_func_array(Array, Array)
#79 /home/reisebil/public_html/206/var/generation/Magento/Framework/App/Http/Interceptor.php(26): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, Array)
#80 /home/reisebil/public_html/206/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#81 /home/reisebil/public_html/206/index.php(43): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#82 {main}
```

**Comment by magefan** [comment]
How your integration on homepage works? Do you use widget or added some layout xml? Can you give some code for blog homepage implementation?
