### ISSUE TITLE
Can't edit blog posts with client side less compilation enabled

### ISSUE THREAD

**Issue by cadetto** [magefan/module-blog#458]
**Describe the bug**
When I try to edit a blog post, I get the following error:
```
TypeError: Magento\Framework\View\Page\Config\Renderer::canTypeBeFont(): Argument #1 ($type) must be of type string, null given, called in /app/vendor/magento/framework/View/Page/Config/Renderer.php on line 360 and defined in /app/vendor/magento/framework/View/Page/Config/Renderer.php:440
Stack trace:
#0 /app/vendor/magento/framework/View/Page/Config/Renderer.php(360): Magento\Framework\View\Page\Config\Renderer->canTypeBeFont(NULL)
#1 /app/vendor/magento/module-developer/Model/View/Page/Config/ClientSideLessCompilation/Renderer.php(75): Magento\Framework\View\Page\Config\Renderer->addDefaultAttributes(NULL, NULL)
#2 /app/vendor/magento/framework/View/Page/Config/Renderer.php(423): Magento\Developer\Model\View\Page\Config\ClientSideLessCompilation\Renderer->addDefaultAttributes(NULL, NULL)
#3 /app/vendor/magento/framework/View/Page/Config/Renderer.php(297): Magento\Framework\View\Page\Config\Renderer->renderAssetHtml(Object(Magento\Framework\View\Asset\PropertyGroup))
#4 /app/vendor/magento/framework/View/Page/Config/Renderer.php(284): Magento\Framework\View\Page\Config\Renderer->renderAssetGroup(Object(Magento\Framework\View\Asset\PropertyGroup))
#5 /app/vendor/magento/module-developer/Model/View/Page/Config/ClientSideLessCompilation/Renderer.php(87): Magento\Framework\View\Page\Config\Renderer->renderAssets(Array)
#6 /app/generated/code/Magento/Developer/Model/View/Page/Config/ClientSideLessCompilation/Renderer/Interceptor.php(23): Magento\Developer\Model\View\Page\Config\ClientSideLessCompilation\Renderer->renderAssets(Array)
#7 /app/vendor/magento/framework/View/Page/Config/Renderer.php(137): Magento\Developer\Model\View\Page\Config\ClientSideLessCompilation\Renderer\Interceptor->renderAssets(Array)
#8 /app/generated/code/Magento/Developer/Model/View/Page/Config/ClientSideLessCompilation/Renderer/Interceptor.php(41): Magento\Framework\View\Page\Config\Renderer->renderHeadContent()
#9 /app/vendor/magento/framework/View/Result/Page.php(252): Magento\Developer\Model\View\Page\Config\ClientSideLessCompilation\Renderer\Interceptor->renderHeadContent()
#10 /app/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#11 /app/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(140): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#12 /app/vendor/magento/framework/App/Http.php(120): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#13 /app/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#14 /app/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#15 /app/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#16 {main}
```
This error only happens when the option of client side less compilation is enabled, and it makes it difficult to develop my store with this module

**Preconditions:**
 - Magento Version: 2.4.5
 - Module Version: 2.10.10
 - PHP Version 8.1.0

**To Reproduce**
1. Go to Store -> settings -> configuration -> advanced-> developer -> frontend development workflow
2. Change the workflow type to client side less compilation
3. Go to Content -> Blog -> Posts
4. Try to edit a blog post

**Expected behavior**
The screen of blog edit should be loading

**Actual behavior**
The screen displays an error

**Comment by magefan** [comment]
Thank you for your report. PR request has been merged and this change will be included in the next release.
